function [coords, atomList] = loadXYZ2Coordinates(filename, sepString, infoLinesN)
%% LOADXYZ2COORDINATES

%%
if nargin < 3
    infoLinesN = 2;
end

if nargin < 2
    sepString = 'generated by VMD';
end

% reg expression for float numbe
regExpFloat = "\s[-+]?[0-9]*\.?[0-9]+";

% reg expression for atom name
regExpAtom = "^\w*";

%% load file
fid = fopen(filename, 'r');

if fid == -1
    fprintf('ERROR: unable to open file %s!\n', filename);
    return;
end

theLines = textscan(fid, '%s', 'delimiter', '\n');
theLines = theLines{1};
fclose(fid);

%%
sepIdx = cellfun(@(s) strcmp(s, sepString), theLines);
sepAt = find(sepIdx);

% number of atoms
atomN = diff(sepAt);
if any(atomN ~= atomN(1))
    warning('Atom numbers are not the same in different frames!');
end
atomN = atomN(1)-infoLinesN; % remove lines of information

% number of frames
frameN = sum(sepIdx);

% initialization
coords = nan(atomN, 3, frameN);
atomList = cell(atomN, 1);

% read line by line
for iF = 1:numel(sepAt)
    for iN = 1:atomN
        % get atom name
        tempAtomName = regexp(theLines{sepAt(iF)+iN}, regExpAtom, 'match');
        tempAtomName = strtrim(tempAtomName{1});
        
        % get coordinates
        tempCoords = regexp(theLines{sepAt(iF)+iN}, regExpFloat, 'match');
        tempCoords = cellfun(@str2double, tempCoords);
        
        % store or check atomList
        if iF == 1
            atomList{iN} = tempAtomName;
            tempAtomIdx = iN;
        else
            if strcmp(atomList{iN}, tempAtomName)
                tempAtomIdx = iN;
            else
                tempAtomIdx = find(strcmp(atomList, tempAtomName));
            end
        end
        coords(tempAtomIdx,:,iF) = tempCoords;
    end
end

end

